spring.application.name=app
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:password}
